name: "Build Brotli Static Binary"

on:
  workflow_dispatch:

env:
  VERSION: 1.0.9
  REPOSITORY: "https://github.com/google/brotli/archive/v${{ VERSION }}.zip"

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            os: windows-2019,
            arch: x64,
            name: 'Windows x86_64'
          }
          - {
            os: windows-2019,
            arch: x86,
            name: 'Windows x86'
          }
          - {
            os: ubuntu-latest,
            arch: x64,
            name: 'Ubuntu x86_64'
          }
          - {
            os: macos-latest,
            arch: x64,
            name: 'macOS x86_64'
          }
          - {
            os: windows-latest,
            arch: x64,
            name: 'Windows x86_64'
          }
    name: "OS ${{ matrix.config.name }}"
